#pragma once

#define XMLLINE_MAXCNT			32768
#define XMLLINE_MAXLEN			2048
//--
#define XMLKEY_MAXCNT		1024
#define XMLKEY_NAME_MAXLEN	ObjNameMaxLen
#define XMLKEY_MAXDEPTH		ObjMaxChildren+XMLKEY_NAME_MAXLEN
#define XMLKEY_PATH_MAXLEN	XMLKEY_MAXDEPTH*(XMLKEY_NAME_MAXLEN+1)
#define XMLKEY_PARM_MAXCNT	ObjMaxChildren
#define XMLKEY_PARM_NAME_MAXLEN XMLKEY_NAME_MAXLEN
#define XMLKEY_PARM_VAL_MAXCNT	128
#define XMLKEY_PARM_VAL_MAXLEN	256
