CREATE TABLESPACE HISTORYDATA DATAFILE 'D:\APP\ORACLE12C\ORADATA\ALGO\\HISTORYDATA01.DBF' SIZE 16384M
 BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL AUTOALLOCATE  ONLINE PERMANENT  SEGMENT SPACE MANAGEMENT AUTO;
 
  CREATE USER HISTORY IDENTIFIED BY HistoryPwd DEFAULT TABLESPACE HISTORYDATA TEMPORARY TABLESPACE TEMP;
 grant dba to history;
 
 